#!/usr/bin/env python3
"""
EuroMillions Streamlit UI
========================

Single-page graphical interface for EuroMillions ML prediction system.
Provides data management, model training, prediction generation, and export functionality.
"""

import os
import json
import streamlit as st
import pandas as pd
from datetime import datetime, timedelta
from pathlib import Path
import sys
import hashlib
from collections import Counter

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

# Constants
MAIN_NUM_MIN = 1
MAIN_NUM_MAX = 50
STAR_NUM_MIN = 1
STAR_NUM_MAX = 12
MAIN_NUMBERS_COUNT = 5
STAR_NUMBERS_COUNT = 2
SCORE_MAIN_WEIGHT = 10
SCORE_STAR_WEIGHT = 5
HYBRID_TOP_MAIN = 10
HYBRID_TOP_STARS = 5

# Method descriptions
METHOD_EXPLANATIONS = {
    "topk": "Sélectionne les boules/étoiles avec les plus hautes probabilités",
    "random": "Échantillonnage aléatoire pondéré par les probabilités",
    "hybrid": "Mélange de prédictions top et d'échantillonnage aléatoire",
    "ensemble": "Combine plusieurs algorithmes ML (LightGBM, XGBoost, CatBoost, RandomForest)",
    "advanced_hybrid": "Stratégie hybride avancée (ML + fréquences + motifs + écarts)",
    "enhanced_hybrid": "Version améliorée de la méthode hybride avec ensemble",
    "enhanced_topk": "Version améliorée du top-k avec ensemble",
    "enhanced_random": "Version améliorée de l'aléatoire avec ensemble"
}

from streamlit_adapters import (
    init_full_history,
    update_incremental,
    train_from_scratch,
    train_ensemble_models,
    reload_models,
    get_scores,
    suggest_tickets_ui,
    fetch_last_draws,
    export_all_draws_csv,
    get_system_status
)

# Import backtesting functionality
import numpy as np
from typing import Dict, List, Any

@st.cache_data(ttl=3600)  # Cache for 1 hour
def _get_cached_probabilities():
    """Cache expensive ML probability calculations."""
    import train_models
    main_proba = train_models.score_balls()
    star_proba = train_models.score_stars()
    main_scores = {i: main_proba[i-1] for i in range(MAIN_NUM_MIN, MAIN_NUM_MAX + 1)}
    star_scores = {i: star_proba[i-1] for i in range(STAR_NUM_MIN, STAR_NUM_MAX + 1)}
    return main_scores, star_scores

# Page configuration
st.set_page_config(
    page_title="EuroMillions — Console Graphique", 
    page_icon="🎲", 
    layout="centered"
)

def load_env_settings():
    """Load current .env settings."""
    env_file = Path(".env")
    settings = {
        "STORAGE_DIR": "./data",
        "DB_URL": "sqlite:///./data/draws.db", 
        "USER_AGENT": "EuromillionsPro/1.0 (+contact)",
        "REQUEST_TIMEOUT": "15",
        "MAX_RETRIES": "3"
    }
    
    if env_file.exists():
        with open(env_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    key = key.strip()
                    value = value.strip().strip('"\'')
                    if key in settings:
                        settings[key] = value
    
    return settings

def save_env_settings(settings):
    """Save settings to .env file."""
    env_content = []
    env_content.append("# EuroMillions Configuration")
    env_content.append("# Generated by Streamlit UI")
    env_content.append(f"# Updated: {datetime.now().isoformat()}")
    env_content.append("")
    
    for key, value in settings.items():
        env_content.append(f'{key}="{value}"')
    
    env_content.append("")
    
    with open(".env", 'w', encoding='utf-8') as f:
        f.write('\n'.join(env_content))

def load_config_presets():
    """Load saved configuration presets."""
    preset_file = Path("data/config_presets.json")
    if preset_file.exists():
        with open(preset_file, 'r', encoding='utf-8') as f:
            return json.load(f)
    return {}

def save_config_preset(name: str, config: dict):
    """Save a configuration preset."""
    presets = load_config_presets()
    presets[name] = {
        **config,
        "saved_at": datetime.now().isoformat()
    }
    preset_file = Path("data/config_presets.json")
    preset_file.parent.mkdir(exist_ok=True)
    with open(preset_file, 'w', encoding='utf-8') as f:
        json.dump(presets, f, indent=2)
    return True

def delete_config_preset(name: str):
    """Delete a configuration preset."""
    presets = load_config_presets()
    if name in presets:
        del presets[name]
        with open("data/config_presets.json", 'w', encoding='utf-8') as f:
            json.dump(presets, f, indent=2)
        return True
    return False

def validate_ticket(main_numbers: list, stars: list, main_scores: dict = None, star_scores: dict = None) -> dict:
    """Validate and score a user ticket."""
    from repository import get_repository
    
    result = {
        "valid": True,
        "errors": [],
        "warnings": [],
        "score": 0,
        "probability": 0,
        "historical_matches": [],
        "suggestions": []
    }
    
    # Validation
    if len(main_numbers) != MAIN_NUMBERS_COUNT:
        result["valid"] = False
        result["errors"].append(f"Doit contenir exactement {MAIN_NUMBERS_COUNT} numéros principaux")
    
    if len(stars) != STAR_NUMBERS_COUNT:
        result["valid"] = False
        result["errors"].append(f"Doit contenir exactement {STAR_NUMBERS_COUNT} étoiles")
    
    if any(n < MAIN_NUM_MIN or n > MAIN_NUM_MAX for n in main_numbers):
        result["valid"] = False
        result["errors"].append(f"Numéros principaux doivent être entre {MAIN_NUM_MIN} et {MAIN_NUM_MAX}")
    
    if any(s < STAR_NUM_MIN or s > STAR_NUM_MAX for s in stars):
        result["valid"] = False
        result["errors"].append(f"Étoiles doivent être entre {STAR_NUM_MIN} et {STAR_NUM_MAX}")
    
    if len(set(main_numbers)) != len(main_numbers):
        result["valid"] = False
        result["errors"].append("Numéros principaux en double détectés")
    
    if len(set(stars)) != len(stars):
        result["valid"] = False
        result["errors"].append("Étoiles en double détectées")
    
    if not result["valid"]:
        return result
    
    # Calculate probability score
    if main_scores and star_scores:
        main_prob_sum = sum(main_scores.get(n, (n, 0))[1] if isinstance(main_scores.get(n), tuple) else main_scores.get(n, 0) for n in main_numbers)
        star_prob_sum = sum(star_scores.get(s, (s, 0))[1] if isinstance(star_scores.get(s), tuple) else star_scores.get(s, 0) for s in stars)
        result["probability"] = (main_prob_sum + star_prob_sum) / (MAIN_NUMBERS_COUNT + STAR_NUMBERS_COUNT)
        result["score"] = result["probability"] * 100
    
    # Check historical matches
    repo = get_repository()
    all_draws = repo.all_draws_df()
    
    for idx, row in all_draws.tail(100).iterrows():
        draw_main = [row['n1'], row['n2'], row['n3'], row['n4'], row['n5']]
        draw_stars = [row['s1'], row['s2']]
        
        main_matches = len(set(main_numbers) & set(draw_main))
        star_matches = len(set(stars) & set(draw_stars))
        
        if main_matches >= 3 or (main_matches >= 2 and star_matches >= 1):
            result["historical_matches"].append({
                "date": row['draw_date'],
                "main_matches": main_matches,
                "star_matches": star_matches
            })
    
    # Warnings and suggestions
    if all(n % 2 == 0 for n in main_numbers):
        result["warnings"].append("Tous les numéros sont pairs - très rare")
        result["suggestions"].append("Essayez un mélange de pairs et impairs")
    
    if all(n % 2 == 1 for n in main_numbers):
        result["warnings"].append("Tous les numéros sont impairs - très rare")
        result["suggestions"].append("Essayez un mélange de pairs et impairs")
    
    consecutive = sum(1 for i in range(len(sorted(main_numbers))-1) if sorted(main_numbers)[i+1] - sorted(main_numbers)[i] == 1)
    if consecutive >= 3:
        result["warnings"].append(f"{consecutive} numéros consécutifs détectés")
    
    return result

def get_hot_cold_numbers(n_draws: int = 50) -> dict:
    """Get hot and cold numbers from recent draws."""
    from repository import get_repository
    repo = get_repository()
    recent_draws = repo.all_draws_df().tail(n_draws)
    
    main_freq = Counter()
    star_freq = Counter()
    
    for _, row in recent_draws.iterrows():
        for i in range(1, 6):
            main_freq[row[f'n{i}']] += 1
        for i in range(1, 3):
            star_freq[row[f's{i}']] += 1
    
    hot_main = main_freq.most_common(10)
    cold_main = [(n, main_freq.get(n, 0)) for n in range(MAIN_NUM_MIN, MAIN_NUM_MAX + 1) if main_freq.get(n, 0) <= 2]
    
    hot_stars = star_freq.most_common(5)
    cold_stars = [(s, star_freq.get(s, 0)) for s in range(STAR_NUM_MIN, STAR_NUM_MAX + 1) if star_freq.get(s, 0) == 0]
    
    return {
        "hot_main": hot_main,
        "cold_main": sorted(cold_main, key=lambda x: x[1])[:10],
        "hot_stars": hot_stars,
        "cold_stars": cold_stars,
        "n_draws": n_draws
    }

def get_next_draw_info() -> dict:
    """Get information about the next EuroMillions draw."""
    # EuroMillions draws on Tuesday and Friday
    now = datetime.now()
    days_ahead = (1 - now.weekday()) % 7  # Tuesday = 1
    if days_ahead == 0 and now.hour >= 20:  # After 8 PM on Tuesday
        days_ahead = 7
    
    next_tuesday = now + timedelta(days=days_ahead)
    
    days_ahead_friday = (4 - now.weekday()) % 7  # Friday = 4
    if days_ahead_friday == 0 and now.hour >= 20:
        days_ahead_friday = 7
    
    next_friday = now + timedelta(days=days_ahead_friday)
    
    next_draw = min(next_tuesday, next_friday, key=lambda d: abs((d - now).total_seconds()))
    if next_draw < now:
        next_draw = max(next_tuesday, next_friday)
    
    time_until = next_draw - now
    
    return {
        "next_draw": next_draw,
        "days": time_until.days,
        "hours": time_until.seconds // 3600,
        "minutes": (time_until.seconds % 3600) // 60,
        "day_name": next_draw.strftime("%A"),
        "date_str": next_draw.strftime("%d/%m/%Y")
    }

def save_performance_tracking(prediction: dict):
    """Save a prediction for performance tracking."""
    tracking_file = Path("data/performance_tracking.json")
    tracking_file.parent.mkdir(exist_ok=True)
    
    predictions = []
    if tracking_file.exists():
        with open(tracking_file, 'r', encoding='utf-8') as f:
            predictions = json.load(f)
    
    predictions.append({
        **prediction,
        "id": hashlib.md5(json.dumps(prediction, sort_keys=True).encode()).hexdigest()[:8],
        "created_at": datetime.now().isoformat()
    })
    
    # Keep only last 100 predictions
    predictions = predictions[-100:]
    
    with open(tracking_file, 'w', encoding='utf-8') as f:
        json.dump(predictions, f, indent=2)

def load_performance_tracking() -> list:
    """Load performance tracking data."""
    tracking_file = Path("data/performance_tracking.json")
    if tracking_file.exists():
        with open(tracking_file, 'r', encoding='utf-8') as f:
            return json.load(f)
    return []

def check_predictions_vs_draws() -> dict:
    """Check predictions against actual draws."""
    from repository import get_repository
    
    predictions = load_performance_tracking()
    repo = get_repository()
    all_draws = repo.all_draws_df()
    
    results = {
        "total_predictions": len(predictions),
        "checked": 0,
        "wins": [],
        "best_match": {"main": 0, "stars": 0},
        "total_matches": {"main": 0, "stars": 0}
    }
    
    for pred in predictions:
        if "tickets" not in pred:
            continue
        
        pred_date = datetime.fromisoformat(pred["created_at"]).date()
        
        for _, draw in all_draws.iterrows():
            draw_date = datetime.fromisoformat(draw['draw_date']).date()
            if draw_date >= pred_date:
                results["checked"] += 1
                draw_main = [draw['n1'], draw['n2'], draw['n3'], draw['n4'], draw['n5']]
                draw_stars = [draw['s1'], draw['s2']]
                
                for ticket in pred["tickets"]:
                    ticket_main = ticket.get('main') or ticket.get('balls', [])
                    ticket_stars = ticket.get('stars', [])
                    
                    main_matches = len(set(ticket_main) & set(draw_main))
                    star_matches = len(set(ticket_stars) & set(draw_stars))
                    
                    if main_matches >= 2:
                        results["wins"].append({
                            "date": draw['draw_date'],
                            "main_matches": main_matches,
                            "star_matches": star_matches,
                            "ticket": ticket
                        })
                    
                    if main_matches > results["best_match"]["main"]:
                        results["best_match"]["main"] = main_matches
                    if star_matches > results["best_match"]["stars"]:
                        results["best_match"]["stars"] = star_matches
                    
                    results["total_matches"]["main"] += main_matches
                    results["total_matches"]["stars"] += star_matches
                break
    
    return results

def generate_ticket_qr(ticket: dict) -> str:
    """Generate QR code data URL for a ticket."""
    try:
        import qrcode
        import io
        import base64
        
        ticket_data = f"EuroMillions: {ticket['balls'][0]}-{ticket['balls'][1]}-{ticket['balls'][2]}-{ticket['balls'][3]}-{ticket['balls'][4]} + {ticket['stars'][0]}-{ticket['stars'][1]}"
        
        qr = qrcode.QRCode(version=1, box_size=10, border=2)
        qr.add_data(ticket_data)
        qr.make(fit=True)
        
        img = qr.make_image(fill_color="black", back_color="white")
        
        buffer = io.BytesIO()
        img.save(buffer, format="PNG")
        buffer.seek(0)
        
        img_base64 = base64.b64encode(buffer.getvalue()).decode()
        return f"data:image/png;base64,{img_base64}"
    
    except ImportError:
        return None

def generate_pdf_tickets(tickets: list, method: str, seed: int) -> bytes:
    """Generate PDF with tickets."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import mm
        from reportlab.pdfgen import canvas
        import io
        
        buffer = io.BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4
        
        # Title
        c.setFont("Helvetica-Bold", 20)
        c.drawString(50, height - 50, "EuroMillions - Tickets Générés")
        
        c.setFont("Helvetica", 10)
        c.drawString(50, height - 70, f"Date: {datetime.now().strftime('%d/%m/%Y %H:%M')}")
        c.drawString(50, height - 85, f"Méthode: {method} | Seed: {seed}")
        
        # Tickets
        y_pos = height - 120
        c.setFont("Helvetica-Bold", 12)
        
        for i, ticket in enumerate(tickets):
            if y_pos < 100:  # New page if needed
                c.showPage()
                y_pos = height - 50
            
            balls = ticket.get('balls') or ticket.get('main', [])
            stars = ticket.get('stars', [])
            
            # Ticket number
            c.setFont("Helvetica-Bold", 11)
            c.drawString(50, y_pos, f"Ticket #{i+1}")
            
            # Numbers
            c.setFont("Helvetica", 10)
            numbers_str = " - ".join(str(b) for b in balls)
            stars_str = " - ".join(str(s) for s in stars)
            
            c.drawString(150, y_pos, f"Numéros: {numbers_str}")
            c.drawString(400, y_pos, f"Étoiles: {stars_str}")
            
            # Line separator
            y_pos -= 25
            c.line(50, y_pos, width - 50, y_pos)
            y_pos -= 15
        
        c.save()
        buffer.seek(0)
        return buffer.getvalue()
    
    except ImportError:
        return None

def format_tickets_display(tickets):
    """Format enhanced tickets for display with confidence scores."""
    if not tickets:
        return "Aucun ticket généré"
    
    display_lines = []
    for ticket in tickets:
        balls_str = ticket['balls_str']
        stars_str = ticket['stars_str']
        
        # Get confidence info
        confidence = ticket.get('confidence', 50.0)
        confidence_level = ticket.get('confidence_level', 'Moyenne')
        method = ticket.get('method', 'unknown')
        
        # Choose confidence emoji
        if confidence >= 80:
            confidence_emoji = "🔥"
        elif confidence >= 65:
            confidence_emoji = "⚡"
        elif confidence >= 50:
            confidence_emoji = "✨"
        else:
            confidence_emoji = "💫"
        
        # Format with confidence and method info
        ticket_display = f"""🎫 **Ticket {ticket['ticket_id']}** {confidence_emoji}

   {balls_str}
   ⭐ {stars_str}
   
   📊 **Confiance:** {confidence}% ({confidence_level})
   🎯 **Méthode:** {method}"""
        
        display_lines.append(ticket_display)
    
    return '\n\n---\n\n'.join(display_lines)


def _extract_probabilities(scores: dict, num_range: range) -> np.ndarray:
    """Extract probabilities from score dictionary handling both tuples and floats."""
    import numpy as np
    # Check first element to determine type
    first_val = scores[num_range[0]]
    if isinstance(first_val, tuple):
        return np.array([scores[i][1] for i in num_range])
    else:
        return np.array([scores[i] for i in num_range])

def _generate_hybrid_selection(probs: np.ndarray, top_k: int, select_k: int, nums_range: range) -> list:
    """Generate hybrid selection: top-K weighted random sampling."""
    import numpy as np
    top_idx = np.argsort(probs)[-top_k:]
    top_probs = probs[top_idx]
    top_probs_norm = (top_probs / top_probs.sum()).flatten()
    top_nums = (top_idx + 1).flatten()
    return sorted(np.random.choice(top_nums, size=select_k, replace=False, p=top_probs_norm).tolist())

def _generate_tickets_fast(n: int, method: str, seed: int, main_scores: dict, star_scores: dict) -> List[dict]:
    """
    Génère des tickets RAPIDEMENT en utilisant des probabilités précalculées.
    Évite le rechargement des modèles ML à chaque appel.
    
    Args:
        n: Nombre de tickets
        method: Méthode de génération
        seed: Graine aléatoire
        main_scores: Probabilités précalculées pour les numéros principaux {1:0.12, 2:0.08, ...}
        star_scores: Probabilités précalculées pour les étoiles {1:0.15, 2:0.09, ...}
    
    Returns:
        Liste de tickets {main: [1,2,3,4,5], stars: [1,2]}
    """
    import numpy as np
    
    # Input validation
    if n <= 0:
        raise ValueError(f"n must be positive, got {n}")
    if method not in ["topk", "random", "hybrid", "ensemble", "advanced_hybrid"]:
        raise ValueError(f"Unknown method: {method}")
    
    # Use RandomState for better reproducibility
    rng = np.random.RandomState(seed)
    tickets = []
    
    # Extract probabilities once (optimized)
    main_nums = list(range(MAIN_NUM_MIN, MAIN_NUM_MAX + 1))
    star_nums = list(range(STAR_NUM_MIN, STAR_NUM_MAX + 1))
    main_probs = _extract_probabilities(main_scores, main_nums)
    star_probs = _extract_probabilities(star_scores, star_nums)
    
    for i in range(n):
        if method == "topk":
            # Top-K déterministe
            top_main_idx = np.argsort(main_probs)[-MAIN_NUMBERS_COUNT:]
            top_star_idx = np.argsort(star_probs)[-STAR_NUMBERS_COUNT:]
            main = sorted((top_main_idx + 1).tolist())
            stars = sorted((top_star_idx + 1).tolist())
        
        elif method == "random":
            # Aléatoire pondéré par probabilités
            main_probs_norm = main_probs / main_probs.sum()
            star_probs_norm = star_probs / star_probs.sum()
            main = sorted(rng.choice(main_nums, size=MAIN_NUMBERS_COUNT, replace=False, p=main_probs_norm).tolist())
            stars = sorted(rng.choice(star_nums, size=STAR_NUMBERS_COUNT, replace=False, p=star_probs_norm).tolist())
        
        elif method in ["hybrid", "ensemble", "advanced_hybrid"]:
            # Hybrid selection: top-K weighted random
            # Note: ensemble/advanced_hybrid use same fast approximation in backtesting
            main = _generate_hybrid_selection(main_probs, HYBRID_TOP_MAIN, MAIN_NUMBERS_COUNT, main_nums)
            stars = _generate_hybrid_selection(star_probs, HYBRID_TOP_STARS, STAR_NUMBERS_COUNT, star_nums)
        
        else:
            # Fallback: uniform random
            main = sorted(rng.choice(main_nums, size=MAIN_NUMBERS_COUNT, replace=False).tolist())
            stars = sorted(rng.choice(star_nums, size=STAR_NUMBERS_COUNT, replace=False).tolist())
        
        tickets.append({
            'main': main,
            'stars': stars
        })
    
    return tickets


def run_backtesting(seeds: List[int], methods: List[str], n_draws: int, n_tickets: int) -> pd.DataFrame:
    """
    Lance le backtesting OPTIMISÉ pour trouver les meilleures configurations.
    Précalcule les probabilités ML UNE SEULE FOIS au début pour accélérer drastiquement.
    
    Args:
        seeds: Liste des graines à tester
        methods: Liste des méthodes à tester
        n_draws: Nombre de tirages récents à utiliser
        n_tickets: Nombre de tickets par tirage
        
    Returns:
        DataFrame avec les résultats
    """
    from repository import get_repository
    import train_models
    import time
    
    repo = get_repository()
    all_draws = repo.all_draws_df()
    test_draws = all_draws.tail(n_draws)
    
    # ====== PRÉPARATION DES DONNÉES ======
    # Convertir les colonnes n1-n5, s1-s2 en listes 'main' et 'stars' (vectorized)
    test_draws = test_draws.copy()
    test_draws['main'] = test_draws[['n1', 'n2', 'n3', 'n4', 'n5']].values.tolist()
    test_draws['stars'] = test_draws[['s1', 's2']].values.tolist()
    
    # Vérification des données
    if len(test_draws) == 0:
        st.error("❌ Aucun tirage trouvé dans la base de données !")
        return pd.DataFrame()
    
    st.info(f"📊 {len(test_draws)} tirages historiques chargés pour le backtesting")
    
    # Afficher un exemple de tirage pour vérification
    first_draw = test_draws.iloc[0]
    st.text(f"Exemple: {first_draw['main']} + {first_draw['stars']}")
    
    # ====== OPTIMISATION MAJEURE ======
    # Précalculer les probabilités ML UNE SEULE FOIS (au lieu de les recalculer des milliers de fois)
    status_precalc = st.empty()
    status_precalc.text("⚡ Optimisation : Précalcul des probabilités ML (une seule fois)...")
    
    try:
        # Utiliser le cache Streamlit pour les probabilités
        main_scores, star_scores = _get_cached_probabilities()
        status_precalc.text("✅ Probabilités ML chargées depuis le cache")
        time.sleep(0.5)
        status_precalc.empty()
    except Exception as e:
        status_precalc.text(f"⚠️ Erreur lors du chargement des probabilités: {str(e)}")
        import traceback
        st.error(traceback.format_exc())
        main_scores = None
        star_scores = None
    
    results = []
    total_tests = len(seeds) * len(methods)
    progress_bar = st.progress(0)
    status_text = st.empty()
    current_test = 0
    start_time = time.time()
    
    for seed in seeds:
        for method in methods:
            current_test += 1
            progress_pct = current_test / total_tests
            progress_bar.progress(progress_pct)
            
            # Calculate ETA
            elapsed = time.time() - start_time
            if current_test > 1:
                eta_seconds = (elapsed / (current_test - 1)) * (total_tests - current_test)
                eta_str = f" | ETA: {int(eta_seconds)}s"
            else:
                eta_str = ""
            
            status_text.text(f"⚡ Test {current_test}/{total_tests} ({progress_pct*100:.1f}%): seed={seed}, method={method}{eta_str}")
            
            total_main_matches = 0
            total_star_matches = 0
            total_score = 0
            best_result = {'main': 0, 'stars': 0}
            jackpot_count = 0
            rank2_count = 0
            rank3_count = 0
            any_win_count = 0
            
            for idx, actual_draw in test_draws.iterrows():
                try:
                    # ====== GÉNÉRATION OPTIMISÉE ======
                    # IMPORTANT: Pour le backtesting, TOUTES les méthodes utilisent _generate_tickets_fast
                    # avec les probabilités précalculées pour éviter de prendre des heures
                    # Les méthodes ensemble/advanced_hybrid utiliseront une approximation rapide
                    if main_scores and star_scores:
                        tickets = _generate_tickets_fast(n_tickets, method, seed, main_scores, star_scores)
                    else:
                        # Fallback si précalcul impossible (ne devrait jamais arriver)
                        tickets = suggest_tickets_ui(
                            n=n_tickets,
                            method=method,
                            seed=seed,
                            use_ensemble=False
                        )
                    
                    # CORRECTIF: Extraire les numéros du DataFrame (colonnes n1-n5, s1-s2)
                    actual_main = [actual_draw['n1'], actual_draw['n2'], actual_draw['n3'], 
                                   actual_draw['n4'], actual_draw['n5']]
                    actual_stars = [actual_draw['s1'], actual_draw['s2']]
                    
                    # Évaluer chaque ticket
                    for ticket in tickets:
                        # Normaliser la structure: 'balls' ou 'main' pour les numéros principaux
                        ticket_main = ticket.get('main') or ticket.get('balls', [])
                        ticket_stars = ticket.get('stars', [])
                        
                        main_matches = len(set(ticket_main) & set(actual_main))
                        star_matches = len(set(ticket_stars) & set(actual_stars))
                        
                        total_main_matches += main_matches
                        total_star_matches += star_matches
                        score = main_matches * SCORE_MAIN_WEIGHT + star_matches * SCORE_STAR_WEIGHT
                        total_score += score
                        
                        # Meilleur résultat
                        if (main_matches > best_result['main'] or 
                            (main_matches == best_result['main'] and star_matches > best_result['stars'])):
                            best_result = {'main': main_matches, 'stars': star_matches}
                        
                        # Compter les gains
                        if main_matches == 5 and star_matches == 2:
                            jackpot_count += 1
                        elif main_matches == 5 and star_matches == 1:
                            rank2_count += 1
                        elif main_matches == 5 and star_matches == 0:
                            rank3_count += 1
                        
                        if main_matches >= 2 or star_matches >= 1:
                            any_win_count += 1
                            
                except Exception as e:
                    # Log detailed error information for debugging
                    import traceback
                    error_msg = f"❌ Erreur configuration: seed={seed}, method={method}, tirage={idx}"
                    error_detail = f"Type: {type(e).__name__}, Message: {str(e)}"
                    st.warning(f"{error_msg}\n{error_detail}")
                    # Print full traceback to console for developers
                    print(f"\n{'='*60}")
                    print(error_msg)
                    print(error_detail)
                    print(traceback.format_exc())
                    print('='*60)
                    continue
            
            n_total_tickets = n_draws * n_tickets
            
            results.append({
                'seed': seed,
                'method': method,
                'avg_score': total_score / n_total_tickets if n_total_tickets > 0 else 0,
                'avg_main': total_main_matches / n_total_tickets if n_total_tickets > 0 else 0,
                'avg_stars': total_star_matches / n_total_tickets if n_total_tickets > 0 else 0,
                'best_main': best_result['main'],
                'best_stars': best_result['stars'],
                'jackpots': jackpot_count,
                'rank2': rank2_count,
                'rank3': rank3_count,
                'any_win': any_win_count,
                'win_rate': (any_win_count / n_total_tickets * 100) if n_total_tickets > 0 else 0
            })
    
    progress_bar.empty()
    status_text.empty()
    
    df_results = pd.DataFrame(results)
    df_results = df_results.sort_values('avg_score', ascending=False)
    
    return df_results


def main():
    """Main Streamlit application."""
    
    # Title and header
    st.title("🎲 EuroMillions — Console Graphique")
    st.markdown("Interface de gestion complète pour le système de prédiction EuroMillions")
    
    # Smart Suggestions Engine
    try:
        from repository import get_repository
        repo = get_repository()
        all_draws = repo.all_draws_df()
        
        suggestions = []
        
        # Check data freshness
        if not all_draws.empty:
            last_draw_date = datetime.fromisoformat(all_draws.iloc[-1]['draw_date'])
            days_since = (datetime.now() - last_draw_date).days
            
            if days_since > 7:
                suggestions.append({
                    "type": "warning",
                    "icon": "⚠️",
                    "text": f"Données obsolètes ({days_since} jours) - Rafraîchissez depuis la FDJ",
                    "action": "Scroller vers 'Scraping FDJ'"
                })
            elif days_since <= 1:
                suggestions.append({
                    "type": "success",
                    "icon": "✅",
                    "text": "Données à jour! Prêt pour de nouvelles prédictions",
                    "action": None
                })
        
        # Check model status
        model_file = Path("models/main_model.pkl")
        if model_file.exists():
            model_age_days = (datetime.now() - datetime.fromtimestamp(model_file.stat().st_mtime)).days
            if model_age_days > 30:
                suggestions.append({
                    "type": "info",
                    "icon": "🔄",
                    "text": f"Modèles entraînés il y a {model_age_days} jours - Réentraînement recommandé",
                    "action": "Section 'Entraînement ML'"
                })
        else:
            suggestions.append({
                "type": "error",
                "icon": "❌",
                "text": "Modèles ML non entraînés - Entraînez avant de générer des tickets",
                "action": "Allez à 'Entraînement ML'"
            })
        
        # Check backtesting results
        if len(all_draws) >= 50:
            suggestions.append({
                "type": "info",
                "icon": "🔬",
                "text": "Assez de données pour un backtesting complet - Testez vos configurations",
                "action": "Section 'Backtesting'"
            })
        
        # Check hot numbers
        hot_cold = get_hot_cold_numbers(20)
        if hot_cold["hot_main"]:
            hot_nums = [str(n[0]) for n in hot_cold["hot_main"][:3]]
            suggestions.append({
                "type": "success",
                "icon": "🔥",
                "text": f"Numéros chauds actuels: {', '.join(hot_nums)}",
                "action": "Voir 'Analyse Historique'"
            })
        
        # Display suggestions
        if suggestions:
            for sug in suggestions[:3]:  # Show max 3 suggestions
                if sug["type"] == "warning":
                    st.warning(f"{sug['icon']} {sug['text']}")
                elif sug["type"] == "error":
                    st.error(f"{sug['icon']} {sug['text']}")
                elif sug["type"] == "success":
                    st.success(f"{sug['icon']} {sug['text']}")
                else:
                    st.info(f"{sug['icon']} {sug['text']}")
    
    except Exception as e:
        pass  # Silently fail - suggestions are non-critical
    
    st.markdown("---")
    
    # Sidebar configuration
    with st.sidebar:
        # Draw countdown
        next_draw = get_next_draw_info()
        st.markdown(f"### 🎰 Prochain tirage")
        st.info(f"**{next_draw['day_name']} {next_draw['date_str']}**")
        if next_draw['days'] == 0:
            st.markdown(f"⏰ Dans **{next_draw['hours']}h {next_draw['minutes']}min**")
        else:
            st.markdown(f"📅 Dans **{next_draw['days']} jours**")
        
        st.markdown("---")
        
        # Configuration Presets
        st.header("💾 Préréglages")
        presets = load_config_presets()
        
        if presets:
            preset_names = list(presets.keys())
            selected_preset = st.selectbox(
                "Charger une configuration",
                ["-- Nouveau --"] + preset_names,
                key="preset_selector"
            )
            
            col1, col2 = st.columns(2)
            with col1:
                if selected_preset != "-- Nouveau --" and st.button("📥 Charger", use_container_width=True):
                    preset_config = presets[selected_preset]
                    st.session_state.update(preset_config)
                    st.success(f"✅ {selected_preset} chargé!")
                    st.rerun()
            
            with col2:
                if selected_preset != "-- Nouveau --" and st.button("🗑️ Supprimer", use_container_width=True):
                    delete_config_preset(selected_preset)
                    st.success("Supprimé!")
                    st.rerun()
        
        st.markdown("---")
        
        st.header("🎯 Suggestions")
        
        # Suggestion parameters
        n_tickets = st.slider(
            "Nombre de tickets",
            min_value=1,
            max_value=20,
            value=10,
            help="Nombre de combinaisons à générer"
        )
        
        method = st.selectbox(
            "Méthode de génération",
            options=["hybrid", "ensemble", "advanced_hybrid", "topk", "random"],
            index=0,
            help="Stratégie de sélection des numéros"
        )
        
        # Advanced options
        st.subheader("🔧 Options avancées")
        
        use_ensemble = st.checkbox(
            "Utiliser les modèles d'ensemble",
            value=True,
            help="Combine plusieurs algorithmes ML pour de meilleures prédictions"
        )
        
        # Hybrid strategy weights (only for advanced_hybrid)
        if method == "advanced_hybrid":
            st.subheader("⚖️ Poids de la stratégie hybride")
            
            col1, col2 = st.columns(2)
            with col1:
                ml_weight = st.slider("ML", 0.0, 1.0, 0.4, 0.1, help="Poids des prédictions ML")
                freq_weight = st.slider("Fréquence", 0.0, 1.0, 0.3, 0.1, help="Poids de l'analyse de fréquence")
            
            with col2:
                pattern_weight = st.slider("Motifs", 0.0, 1.0, 0.2, 0.1, help="Poids de l'analyse des motifs")
                gap_weight = st.slider("Écarts", 0.0, 1.0, 0.1, 0.1, help="Poids de l'analyse des écarts")
            
            # Normalize weights
            total_weight = ml_weight + freq_weight + pattern_weight + gap_weight
            if total_weight > 0:
                hybrid_weights = {
                    "ml_weight": ml_weight / total_weight,
                    "freq_weight": freq_weight / total_weight,
                    "pattern_weight": pattern_weight / total_weight,
                    "gap_weight": gap_weight / total_weight
                }
            else:
                hybrid_weights = None
        else:
            hybrid_weights = None
        
        seed = st.number_input(
            "Graine aléatoire",
            min_value=1,
            max_value=9999,
            value=42,
            help="Pour reproductibilité des résultats"
        )
        
        st.markdown("---")
        
        # Settings expander
        with st.expander("⚙️ Paramètres (.env)"):
            st.subheader("Configuration système")
            
            # Load current settings
            current_settings = load_env_settings()
            
            # Settings form
            with st.form("env_settings"):
                new_settings = {}
                
                new_settings["STORAGE_DIR"] = st.text_input(
                    "Répertoire de stockage",
                    value=current_settings["STORAGE_DIR"],
                    help="Dossier pour les données"
                )
                
                new_settings["DB_URL"] = st.text_input(
                    "URL de base de données",
                    value=current_settings["DB_URL"],
                    help="Chemin vers la base SQLite"
                )
                
                new_settings["USER_AGENT"] = st.text_input(
                    "User Agent",
                    value=current_settings["USER_AGENT"],
                    help="Identification pour les requêtes web"
                )
                
                new_settings["REQUEST_TIMEOUT"] = st.text_input(
                    "Timeout requêtes (sec)",
                    value=current_settings["REQUEST_TIMEOUT"],
                    help="Délai d'attente des requêtes"
                )
                
                new_settings["MAX_RETRIES"] = st.text_input(
                    "Nombre de tentatives",
                    value=current_settings["MAX_RETRIES"],
                    help="Retries en cas d'échec"
                )
                
                if st.form_submit_button("💾 Enregistrer paramètres"):
                    try:
                        save_env_settings(new_settings)
                        st.success("✅ Paramètres sauvegardés dans .env")
                        st.rerun()
                    except Exception as e:
                        st.error(f"❌ Erreur lors de la sauvegarde: {e}")
    
    # Main content sections
    
    # Section 1: Initialization & Updates
    st.header("🔧 Initialisation & Mise à jour")
    
    col1, col2 = st.columns(2)
    
    with col1:
        if st.button("📥 Télécharger l'historique & Initialiser", use_container_width=True):
            with st.spinner("Téléchargement de l'historique complet..."):
                try:
                    result = init_full_history()
                    
                    if result.get("success", False):
                        st.success(f"✅ {result['message']}")
                        st.json(result)
                    else:
                        st.error(f"❌ {result['message']}")
                        st.json(result)
                        
                except Exception as e:
                    st.error(f"❌ Erreur lors de l'initialisation: {e}")
    
    with col2:
        if st.button("🔄 Mettre à jour (derniers tirages)", use_container_width=True):
            with st.spinner("Mise à jour des derniers tirages..."):
                try:
                    result = update_incremental()
                    
                    if result.get("success", False):
                        st.success(f"✅ {result['message']}")
                        st.json(result)
                    else:
                        st.error(f"❌ {result['message']}")
                        st.json(result)
                        
                except Exception as e:
                    st.error(f"❌ Erreur lors de la mise à jour: {e}")
    
    st.markdown("---")
    
    # Section 2: Training
    st.header("🧠 Entraînement")
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        if st.button("🏋️ Entraîner (from scratch)", use_container_width=True):
            with st.spinner("Entraînement des modèles en cours..."):
                try:
                    result = train_from_scratch()
                    
                    if result.get("success", False):
                        st.success(f"✅ {result['message']}")
                        
                        # Display training metrics
                        metrics_col1, metrics_col2 = st.columns(2)
                        with metrics_col1:
                            if result.get("main_logloss"):
                                st.metric("Log-loss boules principales", f"{result['main_logloss']:.4f}")
                        with metrics_col2:
                            if result.get("star_logloss"):
                                st.metric("Log-loss étoiles", f"{result['star_logloss']:.4f}")
                        
                        if result.get("training_data_size"):
                            st.info(f"📊 Données d'entraînement: {result['training_data_size']} tirages")
                    else:
                        st.error(f"❌ {result['message']}")
                        
                except Exception as e:
                    st.error(f"❌ Erreur lors de l'entraînement: {e}")
    
    with col2:
        if st.button("🤖 Ensemble de modèles", use_container_width=True):
            with st.spinner("Entraînement des modèles d'ensemble..."):
                try:
                    result = train_ensemble_models()
                    
                    if result.get("success", False):
                        st.success(f"✅ {result['message']}")
                        
                        if result.get("models_trained"):
                            st.info(f"🎯 Modèles entraînés: {', '.join(result['models_trained'])}")
                        
                        if result.get("performance"):
                            perf = result["performance"]
                            metrics_col1, metrics_col2 = st.columns(2)
                            with metrics_col1:
                                if "ensemble_score" in perf:
                                    st.metric("Score d'ensemble", f"{perf['ensemble_score']:.4f}")
                            with metrics_col2:
                                if "best_model" in perf:
                                    st.metric("Meilleur modèle", perf["best_model"])
                    else:
                        st.warning(f"⚠️ {result['message']}")
                        
                except Exception as e:
                    st.error(f"❌ Erreur lors de l'entraînement d'ensemble: {e}")
    
    with col3:
        if st.button("📦 Recharger le modèle", use_container_width=True):
            with st.spinner("Rechargement du modèle..."):
                try:
                    result = reload_models()
                    
                    if result.get("success", False):
                        st.success(f"✅ {result['message']}")
                        
                        if result.get("trained_at"):
                            st.info(f"📅 Entraîné le: {result['trained_at']}")
                    else:
                        st.error(f"❌ {result['message']}")
                        
                except Exception as e:
                    st.error(f"❌ Erreur lors du rechargement: {e}")
    
    st.markdown("---")
    
    # Section 3: Current Probabilities
    st.header("📊 Probabilités actuelles")
    
    if st.button("🔄 Actualiser les probabilités"):
        with st.spinner("Calcul des probabilités..."):
            try:
                balls_df, stars_df = get_scores()
                
                if not balls_df.empty and not stars_df.empty:
                    col1, col2 = st.columns(2)
                    
                    with col1:
                        st.subheader("🎱 Top 15 boules principales")
                        top_balls = balls_df.head(15)
                        st.dataframe(
                            top_balls[['ball', 'percentage', 'rank']].rename(columns={
                                'ball': 'Boule',
                                'percentage': 'Probabilité (%)',
                                'rank': 'Rang'
                            }),
                            use_container_width=True,
                            hide_index=True
                        )
                    
                    with col2:
                        st.subheader("⭐ Top 5 étoiles")
                        top_stars = stars_df.head(5)
                        st.dataframe(
                            top_stars[['star', 'percentage', 'rank']].rename(columns={
                                'star': 'Étoile',
                                'percentage': 'Probabilité (%)',
                                'rank': 'Rang'
                            }),
                            use_container_width=True,
                            hide_index=True
                        )
                else:
                    st.warning("⚠️ Aucune probabilité disponible. Entraînez d'abord un modèle.")
                    
            except Exception as e:
                st.error(f"❌ Erreur lors du calcul des probabilités: {e}")
    
    st.markdown("---")
    
    # Section 3.2: Historical Analysis Dashboard
    st.header("📊 Analyse Historique")
    
    analysis_type = st.radio(
        "Type d'analyse",
        ["🔥 Numéros Chauds/Froids", "📈 Distribution", "🔍 Patterns"],
        horizontal=True
    )
    
    if analysis_type == "🔥 Numéros Chauds/Froids":
        period = st.select_slider(
            "Période d'analyse",
            options=[10, 20, 50, 100, 200],
            value=50,
            format_func=lambda x: f"Derniers {x} tirages"
        )
        
        if st.button("🔍 Analyser", use_container_width=True):
            with st.spinner("Analyse en cours..."):
                hot_cold = get_hot_cold_numbers(period)
                
                col1, col2 = st.columns(2)
                
                with col1:
                    st.subheader("🔥 Numéros CHAUDS")
                    st.caption(f"Plus fréquents sur {period} tirages")
                    
                    hot_main_df = pd.DataFrame(hot_cold["hot_main"], columns=["Numéro", "Fréquence"])
                    hot_main_df["Taux %"] = (hot_main_df["Fréquence"] / period * 100).round(1)
                    st.dataframe(hot_main_df, use_container_width=True, hide_index=True)
                    
                    st.caption("⭐ Étoiles chaudes")
                    hot_stars_df = pd.DataFrame(hot_cold["hot_stars"], columns=["Étoile", "Fréquence"])
                    st.dataframe(hot_stars_df, use_container_width=True, hide_index=True)
                
                with col2:
                    st.subheader("❄️ Numéros FROIDS")
                    st.caption("Moins fréquents - potentiel de retour")
                    
                    cold_main_df = pd.DataFrame(hot_cold["cold_main"], columns=["Numéro", "Fréquence"])
                    st.dataframe(cold_main_df, use_container_width=True, hide_index=True)
                    
                    if hot_cold["cold_stars"]:
                        st.caption("⭐ Étoiles froides")
                        cold_stars_df = pd.DataFrame(hot_cold["cold_stars"], columns=["Étoile", "Fréquence"])
                        st.dataframe(cold_stars_df, use_container_width=True, hide_index=True)
                    else:
                        st.info("Toutes les étoiles sont apparues récemment")
    
    elif analysis_type == "📈 Distribution":
        from repository import get_repository
        repo = get_repository()
        recent_draws = repo.all_draws_df().tail(100)
        
        # Odd/Even analysis
        odd_count = 0
        even_count = 0
        
        for _, row in recent_draws.iterrows():
            for i in range(1, 6):
                if row[f'n{i}'] % 2 == 0:
                    even_count += 1
                else:
                    odd_count += 1
        
        col1, col2 = st.columns(2)
        with col1:
            st.metric("Pairs", f"{even_count} ({even_count/(even_count+odd_count)*100:.1f}%)")
        with col2:
            st.metric("Impairs", f"{odd_count} ({odd_count/(even_count+odd_count)*100:.1f}%)")
        
        st.info("💡 Distribution équilibrée idéale : ~50% pairs, ~50% impairs")
    
    else:  # Patterns
        st.info("🔍 Analyse des patterns communes")
        from repository import get_repository
        repo = get_repository()
        recent_draws = repo.all_draws_df().tail(50)
        
        consecutive_count = 0
        for _, row in recent_draws.iterrows():
            nums = sorted([row['n1'], row['n2'], row['n3'], row['n4'], row['n5']])
            for i in range(len(nums)-1):
                if nums[i+1] - nums[i] == 1:
                    consecutive_count += 1
        
        st.metric("Numéros consécutifs", f"{consecutive_count} occurrences", f"{consecutive_count/50:.1f} par tirage")
        st.caption("Moyenne dans les 50 derniers tirages")
    
    st.markdown("---")
    
    # Section 3.5: Backtesting - Optimisation des paramètres
    st.header("🔬 Backtesting - Optimisation des paramètres")
    
    with st.expander("ℹ️ Qu'est-ce que le backtesting?", expanded=False):
        st.markdown("""
        **Le backtesting permet de tester différentes configurations** (graines + méthodes) 
        sur les tirages passés pour identifier lesquelles auraient donné les meilleurs résultats.
        
        **Pourquoi c'est utile:**
        - 🎯 Trouve la **meilleure graine** automatiquement
        - 📊 Compare objectivement les **différentes méthodes**
        - 🔍 Analyse les performances sur les **tirages réels**
        - 💡 Vous dit **exactement quels paramètres** utiliser
        
        **Note:** Les performances passées ne garantissent pas les résultats futurs, 
        mais permettent d'optimiser vos choix de manière scientifique.
        """)
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("🎲 Graines à tester")
        seed_option = st.radio(
            "Plage de graines",
            options=["Rapide (10 graines)", "Standard (25 graines)", "Complet (50 graines)", "Personnalisé"],
            index=1
        )
        
        if seed_option == "Rapide (10 graines)":
            seeds_to_test = [1, 10, 20, 30, 40, 42, 50, 75, 100, 150]
        elif seed_option == "Standard (25 graines)":
            seeds_to_test = list(range(1, 26))
        elif seed_option == "Complet (50 graines)":
            seeds_to_test = list(range(1, 51))
        else:  # Personnalisé
            seed_start = st.number_input("Graine de début", min_value=1, max_value=9999, value=1)
            seed_end = st.number_input("Graine de fin", min_value=1, max_value=9999, value=50)
            seeds_to_test = list(range(seed_start, seed_end + 1))
        
        st.caption(f"📊 {len(seeds_to_test)} graines à tester")
    
    with col2:
        st.subheader("🎯 Méthodes à tester")
        methods_to_test = st.multiselect(
            "Sélectionnez les méthodes",
            options=["topk", "random", "hybrid", "ensemble", "advanced_hybrid"],
            default=["topk", "random", "hybrid"]
        )
        
        if not methods_to_test:
            st.warning("⚠️ Sélectionnez au moins une méthode")
        
        # Avertissement pour ensemble/advanced_hybrid
        if "ensemble" in methods_to_test or "advanced_hybrid" in methods_to_test:
            st.info("ℹ️ **Note:** Les méthodes ensemble/advanced_hybrid utilisent une approximation rapide dans le backtesting (similaire à hybrid) pour éviter des temps d'exécution de plusieurs heures.")
    
    col3, col4 = st.columns(2)
    
    with col3:
        n_draws_backtest = st.slider(
            "Nombre de tirages à analyser",
            min_value=10,
            max_value=100,
            value=30,
            help="Plus = plus précis mais plus lent"
        )
    
    with col4:
        n_tickets_backtest = st.slider(
            "Tickets par tirage",
            min_value=5,
            max_value=20,
            value=10,
            help="Nombre de tickets générés pour chaque test"
        )
    
    # Estimation du temps
    total_tests = len(seeds_to_test) * len(methods_to_test)
    estimated_time = total_tests * 0.5  # ~0.5 sec par test
    
    st.info(f"⏱️ Tests à effectuer: **{total_tests}** | Durée estimée: **~{estimated_time/60:.1f} minutes**")
    
    if st.button("🚀 Lancer le backtesting", use_container_width=True, type="primary"):
        if not methods_to_test:
            st.error("❌ Veuillez sélectionner au moins une méthode")
        else:
            with st.spinner(f"Backtesting en cours... ({total_tests} tests)"):
                try:
                    df_results = run_backtesting(
                        seeds=seeds_to_test,
                        methods=methods_to_test,
                        n_draws=n_draws_backtest,
                        n_tickets=n_tickets_backtest
                    )
                    
                    if not df_results.empty:
                        st.success("✅ Backtesting terminé!")
                        
                        # Afficher le TOP 10
                        st.subheader("🏆 TOP 10 Meilleures Configurations")
                        
                        top_10 = df_results.head(10).copy()
                        top_10['rank'] = range(1, len(top_10) + 1)
                        
                        # Formater pour l'affichage
                        display_df = top_10[[
                            'rank', 'seed', 'method', 'avg_score', 'avg_main', 
                            'avg_stars', 'best_main', 'best_stars', 'win_rate'
                        ]].copy()
                        
                        display_df.columns = [
                            'Rang', 'Graine', 'Méthode', 'Score Moy', 'Nums Moy', 
                            'Étoiles Moy', 'Meilleur Nums', 'Meilleur Étoiles', 'Taux Gain %'
                        ]
                        
                        # Arrondir les valeurs
                        display_df['Score Moy'] = display_df['Score Moy'].round(2)
                        display_df['Nums Moy'] = display_df['Nums Moy'].round(2)
                        display_df['Étoiles Moy'] = display_df['Étoiles Moy'].round(2)
                        display_df['Taux Gain %'] = display_df['Taux Gain %'].round(1)
                        
                        st.dataframe(
                            display_df,
                            use_container_width=True,
                            hide_index=True
                        )
                        
                        # Recommandation
                        best_config = df_results.iloc[0]
                        st.success(f"""
                        💡 **RECOMMANDATION:**
                        
                        Utilisez **seed={int(best_config['seed'])}** avec la méthode **{best_config['method']}**
                        
                        Cette configuration a obtenu:
                        - Score moyen: **{best_config['avg_score']:.2f}**
                        - Numéros corrects (moy): **{best_config['avg_main']:.2f}/5**
                        - Étoiles correctes (moy): **{best_config['avg_stars']:.2f}/2**
                        - Meilleur résultat: **{int(best_config['best_main'])} numéros + {int(best_config['best_stars'])} étoiles**
                        - Taux de gain: **{best_config['win_rate']:.1f}%**
                        """)
                        
                        # Graphique de comparaison des méthodes
                        st.subheader("📊 Comparaison des méthodes")
                        
                        method_comparison = df_results.groupby('method').agg({
                            'avg_score': 'mean',
                            'avg_main': 'mean',
                            'avg_stars': 'mean',
                            'win_rate': 'mean'
                        }).round(2)
                        
                        st.bar_chart(method_comparison['avg_score'])
                        
                        # Export des résultats
                        st.subheader("💾 Export des résultats")
                        
                        csv_data = df_results.to_csv(index=False)
                        st.download_button(
                            label="📥 Télécharger les résultats (CSV)",
                            data=csv_data,
                            file_name=f"backtest_results_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
                            mime="text/csv",
                            use_container_width=True
                        )
                        
                        # Détails par graine pour la meilleure méthode
                        if len(methods_to_test) > 1:
                            st.subheader("🔍 Détails par graine (meilleure méthode)")
                            best_method = best_config['method']
                            method_details = df_results[df_results['method'] == best_method].head(10)
                            
                            st.line_chart(
                                method_details.set_index('seed')['avg_score'],
                                use_container_width=True
                            )
                    else:
                        st.warning("⚠️ Aucun résultat obtenu")
                        
                except Exception as e:
                    st.error(f"❌ Erreur lors du backtesting: {e}")
                    import traceback
                    st.code(traceback.format_exc())
    
    st.markdown("---")
    
    # Section 3.7: A/B Testing Mode
    st.header("🧪 Mode Test A/B")
    
    with st.expander("⚡ Comparer deux configurations", expanded=False):
        st.markdown("Testez et comparez deux méthodes côte à côte pour identifier la plus performante")
        
        col1, col2 = st.columns(2)
        
        with col1:
            st.subheader("🅰️ Configuration A")
            method_a = st.selectbox(
                "Méthode A",
                options=["hybrid", "ensemble", "advanced_hybrid", "topk", "random"],
                index=0,
                key="ab_method_a"
            )
            seed_a = st.number_input("Seed A", min_value=1, max_value=9999, value=42, key="ab_seed_a")
        
        with col2:
            st.subheader("🅱️ Configuration B")
            method_b = st.selectbox(
                "Méthode B",
                options=["hybrid", "ensemble", "advanced_hybrid", "topk", "random"],
                index=1,
                key="ab_method_b"
            )
            seed_b = st.number_input("Seed B", min_value=1, max_value=9999, value=123, key="ab_seed_b")
        
        n_tickets_ab = st.slider("Nombre de tickets par configuration", 10, 100, 50, 10)
        
        if st.button("▶️ Lancer le test A/B", type="primary", use_container_width=True):
            with st.spinner("Exécution du test A/B..."):
                try:
                    from repository import get_repository
                    repo = get_repository()
                    all_draws = repo.all_draws_df()
                    
                    if len(all_draws) < 30:
                        st.warning("⚠️ Pas assez de données pour un test significatif (minimum 30 tirages)")
                    else:
                        # Split data: train on first 80%, test on last 20%
                        split_idx = int(len(all_draws) * 0.8)
                        test_draws = all_draws.iloc[split_idx:].copy()
                        
                        main_scores, star_scores = _get_cached_probabilities()
                        
                        results_a = {"wins": 0, "total_main": 0, "total_stars": 0, "best_match": (0, 0)}
                        results_b = {"wins": 0, "total_main": 0, "total_stars": 0, "best_match": (0, 0)}
                        
                        # Generate tickets for both configs
                        tickets_a = _generate_tickets_fast(n_tickets_ab, method_a, seed_a, main_scores, star_scores)
                        tickets_b = _generate_tickets_fast(n_tickets_ab, method_b, seed_b, main_scores, star_scores)
                        
                        # Test against each draw
                        for _, draw in test_draws.iterrows():
                            draw_main = [draw['n1'], draw['n2'], draw['n3'], draw['n4'], draw['n5']]
                            draw_stars = [draw['s1'], draw['s2']]
                            
                            # Check config A
                            for ticket in tickets_a:
                                ticket_main = ticket.get('main') or ticket.get('balls', [])
                                ticket_stars = ticket.get('stars', [])
                                
                                main_match = len(set(ticket_main) & set(draw_main))
                                star_match = len(set(ticket_stars) & set(draw_stars))
                                
                                results_a["total_main"] += main_match
                                results_a["total_stars"] += star_match
                                
                                if main_match >= 2:
                                    results_a["wins"] += 1
                                
                                if (main_match, star_match) > results_a["best_match"]:
                                    results_a["best_match"] = (main_match, star_match)
                            
                            # Check config B
                            for ticket in tickets_b:
                                ticket_main = ticket.get('main') or ticket.get('balls', [])
                                ticket_stars = ticket.get('stars', [])
                                
                                main_match = len(set(ticket_main) & set(draw_main))
                                star_match = len(set(ticket_stars) & set(draw_stars))
                                
                                results_b["total_main"] += main_match
                                results_b["total_stars"] += star_match
                                
                                if main_match >= 2:
                                    results_b["wins"] += 1
                                
                                if (main_match, star_match) > results_b["best_match"]:
                                    results_b["best_match"] = (main_match, star_match)
                        
                        # Display results
                        st.success(f"✅ Test complété sur {len(test_draws)} tirages")
                        
                        col1, col2 = st.columns(2)
                        
                        with col1:
                            st.subheader("🅰️ Résultats A")
                            st.metric("Gains (2+)", results_a["wins"])
                            st.metric("Meilleur match", f"{results_a['best_match'][0]}+{results_a['best_match'][1]}")
                            avg_main_a = results_a["total_main"] / (n_tickets_ab * len(test_draws))
                            avg_stars_a = results_a["total_stars"] / (n_tickets_ab * len(test_draws))
                            st.caption(f"Moy: {avg_main_a:.2f} num + {avg_stars_a:.2f} étoiles")
                        
                        with col2:
                            st.subheader("🅱️ Résultats B")
                            st.metric("Gains (2+)", results_b["wins"])
                            st.metric("Meilleur match", f"{results_b['best_match'][0]}+{results_b['best_match'][1]}")
                            avg_main_b = results_b["total_main"] / (n_tickets_ab * len(test_draws))
                            avg_stars_b = results_b["total_stars"] / (n_tickets_ab * len(test_draws))
                            st.caption(f"Moy: {avg_main_b:.2f} num + {avg_stars_b:.2f} étoiles")
                        
                        # Determine winner
                        score_a = results_a["wins"] * 10 + avg_main_a * 5 + avg_stars_a * 3
                        score_b = results_b["wins"] * 10 + avg_main_b * 5 + avg_stars_b * 3
                        
                        if score_a > score_b:
                            st.success(f"🏆 Configuration A gagne avec un score de {score_a:.1f} vs {score_b:.1f}")
                        elif score_b > score_a:
                            st.success(f"🏆 Configuration B gagne avec un score de {score_b:.1f} vs {score_a:.1f}")
                        else:
                            st.info("🤝 Match nul - performances équivalentes")
                
                except Exception as e:
                    st.error(f"❌ Erreur lors du test A/B: {e}")
                    import traceback
                    st.code(traceback.format_exc())
    
    st.markdown("---")
    
    # Section 3.8: Smart Ticket Validator
    st.header("🎲 Validateur de Ticket Intelligent")
    
    with st.expander("✏️ Valider votre ticket personnel", expanded=False):
        st.markdown("Entrez vos numéros pour obtenir une analyse complète")
        
        col1, col2 = st.columns(2)
        
        with col1:
            st.subheader("Numéros principaux (5)")
            user_main = []
            cols = st.columns(5)
            for i in range(5):
                with cols[i]:
                    num = st.number_input(f"N{i+1}", min_value=1, max_value=50, value=1+i*10, key=f"user_main_{i}")
                    user_main.append(num)
        
        with col2:
            st.subheader("Étoiles (2)")
            user_stars = []
            cols = st.columns(2)
            for i in range(2):
                with cols[i]:
                    star = st.number_input(f"E{i+1}", min_value=1, max_value=12, value=1+i*5, key=f"user_star_{i}")
                    user_stars.append(star)
        
        if st.button("🔍 Valider et Analyser", use_container_width=True, type="primary"):
            with st.spinner("Analyse en cours..."):
                try:
                    # Get probabilities for scoring
                    main_scores, star_scores = _get_cached_probabilities()
                    validation = validate_ticket(user_main, user_stars, main_scores, star_scores)
                    
                    if not validation["valid"]:
                        st.error("❌ Ticket invalide")
                        for error in validation["errors"]:
                            st.error(f"• {error}")
                    else:
                        st.success("✅ Ticket valide!")
                        
                        # Display score
                        col1, col2, col3 = st.columns(3)
                        with col1:
                            st.metric("Score ML", f"{validation['score']:.1f}/100")
                        with col2:
                            st.metric("Probabilité", f"{validation['probability']*100:.2f}%")
                        with col3:
                            matches = len(validation["historical_matches"])
                            st.metric("Matches historiques", matches, f"sur 100 tirages")
                        
                        # Warnings
                        if validation["warnings"]:
                            st.warning("⚠️ Avertissements")
                            for warning in validation["warnings"]:
                                st.caption(f"• {warning}")
                        
                        # Suggestions
                        if validation["suggestions"]:
                            st.info("💡 Suggestions d'amélioration")
                            for suggestion in validation["suggestions"]:
                                st.caption(f"• {suggestion}")
                        
                        # Historical matches
                        if validation["historical_matches"]:
                            with st.expander(f"📜 Détail des {len(validation['historical_matches'])} correspondances historiques"):
                                for match in validation["historical_matches"][:10]:
                                    st.caption(f"{match['date']}: {match['main_matches']} numéros + {match['star_matches']} étoiles")
                
                except Exception as e:
                    st.error(f"❌ Erreur lors de la validation: {e}")
    
    st.markdown("---")
    
    # Section 4: Generate Tickets
    st.header("🎫 Générer des tickets 5+2")
    
    if st.button("🎲 Générer les tickets", use_container_width=True):
        with st.spinner(f"Génération de {n_tickets} tickets avec la méthode {method}..."):
            try:
                tickets = suggest_tickets_ui(n_tickets, method, seed, use_ensemble, hybrid_weights)
                
                if tickets:
                    st.success(f"✅ {len(tickets)} tickets générés avec succès!")
                    
                    # Display tickets
                    st.subheader("🎫 Vos tickets EuroMillions")
                    
                    tickets_text = format_tickets_display(tickets)
                    st.markdown(tickets_text)
                    
                    # Prepare download data
                    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                    
                    # CSV format
                    csv_data = []
                    csv_data.append("Ticket,Boule1,Boule2,Boule3,Boule4,Boule5,Etoile1,Etoile2")
                    for ticket in tickets:
                        balls = ticket['balls']
                        stars = ticket['stars']
                        csv_data.append(f"{ticket['ticket_id']},{balls[0]},{balls[1]},{balls[2]},{balls[3]},{balls[4]},{stars[0]},{stars[1]}")
                    csv_content = '\n'.join(csv_data)
                    
                    # JSON format
                    json_content = json.dumps({
                        "generated_at": datetime.now().isoformat(),
                        "method": method,
                        "seed": seed,
                        "tickets": tickets
                    }, indent=2, ensure_ascii=False)
                    
                    # Download buttons
                    col1, col2, col3, col4 = st.columns(4)
                    
                    with col1:
                        st.download_button(
                            label="⬇️ CSV",
                            data=csv_content,
                            file_name=f"euromillions_tickets_{timestamp}.csv",
                            mime="text/csv",
                            use_container_width=True
                        )
                    
                    with col2:
                        st.download_button(
                            label="⬇️ JSON",
                            data=json_content,
                            file_name=f"euromillions_tickets_{timestamp}.json",
                            mime="application/json",
                            use_container_width=True
                        )
                    
                    with col3:
                        # TXT format
                        txt_content = f"EuroMillions Tickets\nGénérés le: {datetime.now().strftime('%d/%m/%Y %H:%M')}\n"
                        txt_content += f"Méthode: {method} | Seed: {seed}\n"
                        txt_content += "=" * 50 + "\n\n"
                        for ticket in tickets:
                            balls = ticket['balls']
                            stars = ticket['stars']
                            txt_content += f"Ticket {ticket['ticket_id']}: {balls[0]}-{balls[1]}-{balls[2]}-{balls[3]}-{balls[4]} + {stars[0]}-{stars[1]}\n"
                        
                        st.download_button(
                            label="⬇️ TXT",
                            data=txt_content,
                            file_name=f"euromillions_tickets_{timestamp}.txt",
                            mime="text/plain",
                            use_container_width=True
                        )
                    
                    with col4:
                        # PDF format
                        pdf_bytes = generate_pdf_tickets(tickets, method, seed)
                        if pdf_bytes:
                            st.download_button(
                                label="⬇️ PDF",
                                data=pdf_bytes,
                                file_name=f"euromillions_tickets_{timestamp}.pdf",
                                mime="application/pdf",
                                use_container_width=True
                            )
                        else:
                            if st.button("📄 PDF", disabled=True, use_container_width=True):
                                pass
                            st.caption("Install reportlab")
                    
                    # QR Code option (expandable)
                    with st.expander("📱 QR Codes pour tickets", expanded=False):
                        st.caption("Scannez ces QR codes pour sauvegarder vos tickets")
                        
                        qr_available = False
                        try:
                            import qrcode
                            qr_available = True
                        except ImportError:
                            st.warning("📦 Module qrcode non installé. Installez avec: pip install qrcode[pil]")
                        
                        if qr_available:
                            cols_per_row = 3
                            for i in range(0, min(len(tickets), 9), cols_per_row):  # Show max 9 QR codes
                                cols = st.columns(cols_per_row)
                                for j, col in enumerate(cols):
                                    if i + j < len(tickets):
                                        ticket = tickets[i + j]
                                        with col:
                                            qr_data_url = generate_ticket_qr(ticket)
                                            if qr_data_url:
                                                st.markdown(f"**Ticket {ticket['ticket_id']}**")
                                                st.markdown(f'<img src="{qr_data_url}" width="150"/>', unsafe_allow_html=True)
                            
                            if len(tickets) > 9:
                                st.info(f"Affichage de 9 QR codes sur {len(tickets)} tickets")
                    
                    # Method explanation
                    st.info(f"**Méthode utilisée:** {method} | **Graine:** {seed}")
                    st.caption(METHOD_EXPLANATIONS.get(method, "Méthode personnalisée"))
                    
                    # Number Distribution Visualizer
                    with st.expander("📊 Distribution des numéros générés", expanded=False):
                        st.subheader("Analyse de couverture")
                        
                        # Count frequency of each number
                        main_freq = Counter()
                        star_freq = Counter()
                        
                        for ticket in tickets:
                            for num in ticket['balls']:
                                main_freq[num] += 1
                            for star in ticket['stars']:
                                star_freq[star] += 1
                        
                        col1, col2 = st.columns(2)
                        
                        with col1:
                            st.caption("🎱 Numéros principaux")
                            
                            # Create DataFrame for better display
                            main_data = []
                            for num in range(MAIN_NUM_MIN, MAIN_NUM_MAX + 1):
                                count = main_freq.get(num, 0)
                                main_data.append({"Numéro": num, "Fréquence": count, "Taux %": f"{count/len(tickets)*100:.1f}"})
                            
                            main_df = pd.DataFrame(main_data)
                            
                            # Show most and least used
                            most_used = main_df.nlargest(5, 'Fréquence')
                            st.markdown("**Top 5 plus utilisés:**")
                            st.dataframe(most_used, hide_index=True, use_container_width=True)
                            
                            least_used = main_df[main_df['Fréquence'] == 0]
                            if not least_used.empty:
                                st.markdown(f"**Non utilisés:** {len(least_used)} numéros")
                                st.caption(", ".join(str(n) for n in least_used['Numéro'].tolist()))
                            else:
                                st.success("✅ Couverture complète!")
                        
                        with col2:
                            st.caption("⭐ Étoiles")
                            
                            star_data = []
                            for star in range(STAR_NUM_MIN, STAR_NUM_MAX + 1):
                                count = star_freq.get(star, 0)
                                star_data.append({"Étoile": star, "Fréquence": count, "Taux %": f"{count/len(tickets)*100:.1f}"})
                            
                            star_df = pd.DataFrame(star_data)
                            st.dataframe(star_df, hide_index=True, use_container_width=True)
                            
                            unused_stars = star_df[star_df['Fréquence'] == 0]
                            if not unused_stars.empty:
                                st.info(f"Non utilisées: {', '.join(str(s) for s in unused_stars['Étoile'].tolist())}")
                        
                        # Coverage metrics
                        total_main_coverage = (len(main_freq) / MAIN_NUM_MAX) * 100
                        total_star_coverage = (len(star_freq) / STAR_NUM_MAX) * 100
                        
                        col1, col2 = st.columns(2)
                        with col1:
                            st.metric("Couverture numéros", f"{total_main_coverage:.1f}%", f"{len(main_freq)}/{MAIN_NUM_MAX}")
                        with col2:
                            st.metric("Couverture étoiles", f"{total_star_coverage:.1f}%", f"{len(star_freq)}/{STAR_NUM_MAX}")
                    
                    # Save configuration preset
                    st.markdown("---")
                    st.subheader("💾 Sauvegarder cette configuration")
                    col1, col2 = st.columns([3, 1])
                    with col1:
                        preset_name = st.text_input(
                            "Nom du préréglage",
                            value=f"{method}_seed{seed}",
                            key="preset_name_input"
                        )
                    with col2:
                        st.write("")
                        st.write("")
                        if st.button("💾 Sauvegarder", use_container_width=True):
                            config = {
                                "n_tickets": n_tickets,
                                "method": method,
                                "seed": seed,
                                "use_ensemble": use_ensemble
                            }
                            if save_config_preset(preset_name, config):
                                st.success(f"✅ Configuration '{preset_name}' sauvegardée!")
                    
                    # Save for performance tracking
                    tracking_data = {
                        "method": method,
                        "seed": seed,
                        "n_tickets": n_tickets,
                        "tickets": tickets[:10]  # Keep first 10 for tracking
                    }
                    save_performance_tracking(tracking_data)
                
                else:
                    st.warning("⚠️ Aucun ticket généré. Vérifiez que les modèles sont entraînés.")
                    
            except Exception as e:
                st.error(f"❌ Erreur lors de la génération: {e}")
    
    st.markdown("---")
    
    # Section 4.5: Performance Tracking
    st.header("📈 Suivi de Performance")
    
    if st.button("🔄 Actualiser les statistiques", use_container_width=True):
        with st.spinner("Analyse des performances..."):
            try:
                perf_data = check_predictions_vs_draws()
                
                if perf_data["total_predictions"] == 0:
                    st.info("ℹ️ Aucune prédiction à analyser. Générez des tickets pour commencer le suivi.")
                else:
                    col1, col2, col3, col4 = st.columns(4)
                    
                    with col1:
                        st.metric("Prédictions", perf_data["total_predictions"])
                    with col2:
                        st.metric("Vérifiées", perf_data["checked"])
                    with col3:
                        st.metric("Meilleur match", f"{perf_data['best_match']['main']}+{perf_data['best_match']['stars']}")
                    with col4:
                        win_count = len(perf_data["wins"])
                        st.metric("Gains (2+)", win_count)
                    
                    if perf_data["wins"]:
                        st.subheader("🏆 Historique des gains")
                        wins_df = pd.DataFrame(perf_data["wins"])
                        display_wins = wins_df[['date', 'main_matches', 'star_matches']].copy()
                        display_wins.columns = ['Date', 'Numéros', 'Étoiles']
                        st.dataframe(display_wins, use_container_width=True, hide_index=True)
                    
                    # Performance insights
                    if perf_data["checked"] > 0:
                        avg_main = perf_data["total_matches"]["main"] / perf_data["checked"]
                        avg_stars = perf_data["total_matches"]["stars"] / perf_data["checked"]
                        
                        st.info(f"📊 Moyenne par ticket: {avg_main:.2f} numéros corrects, {avg_stars:.2f} étoiles correctes")
            
            except Exception as e:
                st.error(f"❌ Erreur lors de l'analyse: {e}")
    
    st.markdown("---")
    
    # Section 5: Manual Draw Entry
    st.header("➕ Ajouter un tirage manuellement")
    
    with st.expander("📝 Saisir un nouveau tirage", expanded=False):
        st.subheader("Informations du tirage")
        
        # Date input
        draw_date = st.date_input(
            "Date du tirage",
            value=datetime.now().date(),
            help="Date du tirage officiel"
        )
        
        col1, col2 = st.columns(2)
        
        with col1:
            st.subheader("🎱 Numéros principaux (1-50)")
            main_numbers = []
            
            # 5 number inputs for main numbers
            for i in range(5):
                num = st.number_input(
                    f"Numéro {i+1}",
                    min_value=1,
                    max_value=50,
                    value=1,
                    key=f"main_{i}",
                    help=f"Numéro principal {i+1} (entre 1 et 50)"
                )
                main_numbers.append(num)
        
        with col2:
            st.subheader("⭐ Étoiles (1-12)")
            stars = []
            
            # 2 star inputs
            for i in range(2):
                star = st.number_input(
                    f"Étoile {i+1}",
                    min_value=1,
                    max_value=12,
                    value=1,
                    key=f"star_{i}",
                    help=f"Étoile {i+1} (entre 1 et 12)"
                )
                stars.append(star)
        
        # Validation and preview
        col1, col2 = st.columns(2)
        
        with col1:
            # Validate inputs
            main_numbers_sorted = sorted(main_numbers)
            stars_sorted = sorted(stars)
            
            # Check for duplicates in main numbers
            main_duplicates = len(main_numbers) != len(set(main_numbers))
            # Check for duplicates in stars
            star_duplicates = len(stars) != len(set(stars))
            
            if main_duplicates:
                st.error("❌ Les numéros principaux doivent être différents")
            elif star_duplicates:
                st.error("❌ Les étoiles doivent être différentes")
            else:
                st.success("✅ Tirage valide")
                
                # Preview
                st.info(f"**Aperçu:** {' - '.join(map(str, main_numbers_sorted))} | ⭐ {' - '.join(map(str, stars_sorted))}")
        
        with col2:
            # Add button
            if st.button("💾 Ajouter le tirage", disabled=main_duplicates or star_duplicates):
                with st.spinner("Ajout du tirage en cours..."):
                    try:
                        # Import here to avoid circular imports
                        from repository import EuromillionsRepository
                        
                        # Create draw ID
                        draw_id = f"EM-{draw_date.strftime('%Y-%m-%d')}"
                        
                        # Prepare draw data
                        draw_data = {
                            'draw_id': draw_id,
                            'draw_date': draw_date.strftime('%Y-%m-%d'),
                            'n1': main_numbers_sorted[0],
                            'n2': main_numbers_sorted[1],
                            'n3': main_numbers_sorted[2],
                            'n4': main_numbers_sorted[3],
                            'n5': main_numbers_sorted[4],
                            's1': stars_sorted[0],
                            's2': stars_sorted[1],
                            'jackpot': None,
                            'prize_table': None,
                            'raw_html': None
                        }
                        
                        # Save to database
                        repo = EuromillionsRepository()
                        result = repo.upsert_draws([draw_data])
                        
                        if result['inserted'] > 0:
                            st.success(f"✅ Tirage ajouté avec succès ! (ID: {draw_id})")
                            st.info("💡 Pensez à re-entraîner les modèles pour inclure ce nouveau tirage")
                        elif result['updated'] > 0:
                            st.warning(f"⚠️ Tirage existant mis à jour (ID: {draw_id})")
                        else:
                            st.error("❌ Échec de l'ajout du tirage")
                            
                    except Exception as e:
                        st.error(f"❌ Erreur lors de l'ajout: {e}")
    
    st.markdown("---")
    
    # Section 6: CSV Import
    st.header("📄 Import CSV")
    
    with st.expander("📂 Importer des tirages depuis un fichier CSV", expanded=False):
        st.subheader("Téléchargement de fichier CSV")
        
        uploaded_file = st.file_uploader(
            "Choisissez un fichier CSV FDJ",
            type=['csv'],
            help="Fichier CSV au format FDJ avec les tirages EuroMillions"
        )
        
        if uploaded_file is not None:
            # Preview file content
            try:
                # Read content once
                import io
                uploaded_file.seek(0)
                content = uploaded_file.read()
                
                # Try different encodings
                encodings = ['utf-8', 'latin1', 'cp1252']
                df_preview = None
                used_encoding = None
                decoded_content = None
                
                for encoding in encodings:
                    try:
                        decoded_content = content.decode(encoding)
                        df_preview = pd.read_csv(io.StringIO(decoded_content), nrows=5)
                        used_encoding = encoding
                        break
                    except (UnicodeDecodeError, pd.errors.ParserError):
                        continue
                
                if df_preview is not None and decoded_content is not None:
                    st.subheader("Aperçu du fichier")
                    st.dataframe(df_preview, use_container_width=True)
                    
                    # Use already decoded content
                    line_count = len(decoded_content.split('\n'))
                    st.caption(f"Encodage détecté: {used_encoding} | Lignes totales: {line_count}")
                    
                    col1, col2 = st.columns(2)
                    
                    with col1:
                        if st.button("🔍 Analyser le fichier complet"):
                            with st.spinner("Analyse du fichier..."):
                                try:
                                    uploaded_file.seek(0)
                                    df_full = pd.read_csv(io.StringIO(content.decode(used_encoding)))
                                    
                                    st.subheader("Statistiques du fichier")
                                    st.metric("Nombre de lignes", len(df_full))
                                    st.metric("Nombre de colonnes", len(df_full.columns))
                                    
                                    # Show column names
                                    st.subheader("Colonnes détectées")
                                    st.write(list(df_full.columns))
                                    
                                except Exception as e:
                                    st.error(f"Erreur lors de l'analyse: {e}")
                    
                    with col2:
                        if st.button("📥 Importer les données"):
                            with st.spinner("Import des données en cours..."):
                                try:
                                    # Save temporarily and import
                                    import tempfile
                                    import os
                                    
                                    # Create temporary file
                                    with tempfile.NamedTemporaryFile(mode='wb', suffix='.csv', delete=False) as tmp_file:
                                        uploaded_file.seek(0)
                                        tmp_file.write(uploaded_file.read())
                                        temp_path = tmp_file.name
                                    
                                    # Import using existing function
                                    import subprocess
                                    import sys
                                    
                                    # Run import script
                                    result = subprocess.run([
                                        sys.executable, 'import_fdj_special.py', temp_path
                                    ], capture_output=True, text=True, cwd=os.getcwd())
                                    
                                    # Clean up
                                    os.unlink(temp_path)
                                    
                                    if result.returncode == 0:
                                        st.success("✅ Import réussi !")
                                        st.text("Sortie:")
                                        st.code(result.stdout)
                                        st.info("💡 Pensez à re-entraîner les modèles avec les nouvelles données")
                                    else:
                                        st.error("❌ Échec de l'import")
                                        st.text("Erreur:")
                                        st.code(result.stderr)
                                        
                                except Exception as e:
                                    st.error(f"❌ Erreur lors de l'import: {e}")
                else:
                    st.error("❌ Impossible de lire le fichier. Vérifiez le format CSV.")
                    
            except Exception as e:
                st.error(f"❌ Erreur lors de la lecture du fichier: {e}")
    
    st.markdown("---")
    
    # Section 7: History
    st.header("🗂️ Historique")
    
    col1, col2 = st.columns(2)
    
    with col1:
        if st.button("📜 Voir les 20 derniers tirages", use_container_width=True):
            with st.spinner("Chargement de l'historique..."):
                try:
                    recent_draws = fetch_last_draws(20)
                    
                    if not recent_draws.empty:
                        st.subheader("📋 Derniers tirages")
                        
                        # Format for display
                        display_df = recent_draws[['draw_date', 'balls', 'stars']].rename(columns={
                            'draw_date': 'Date',
                            'balls': 'Boules principales',
                            'stars': 'Étoiles'
                        })
                        
                        st.dataframe(
                            display_df,
                            use_container_width=True,
                            hide_index=True
                        )
                    else:
                        st.warning("⚠️ Aucun tirage trouvé dans l'historique.")
                        
                except Exception as e:
                    st.error(f"❌ Erreur lors du chargement: {e}")
    
    with col2:
        if st.button("⬇️ Exporter l'historique (CSV)", use_container_width=True):
            with st.spinner("Préparation de l'export..."):
                try:
                    filename, csv_bytes = export_all_draws_csv()
                    
                    if csv_bytes:
                        st.download_button(
                            label="📁 Télécharger l'historique complet",
                            data=csv_bytes,
                            file_name=filename,
                            mime="text/csv",
                            use_container_width=True
                        )
                        
                        file_size = len(csv_bytes)
                        st.success(f"✅ Export prêt: {filename} ({file_size:,} octets)")
                    else:
                        st.warning("⚠️ Aucune donnée à exporter.")
                        
                except Exception as e:
                    st.error(f"❌ Erreur lors de l'export: {e}")
    
    # Footer with system status
    st.markdown("---")
    
    with st.expander("ℹ️ État du système"):
        try:
            status = get_system_status()
            
            col1, col2 = st.columns(2)
            
            with col1:
                st.subheader("📊 Données")
                if status.get("data", {}).get("available", False):
                    data_info = status["data"]
                    st.success(f"✅ {data_info['count']} tirages disponibles")
                    if data_info.get("first_date") and data_info.get("last_date"):
                        st.caption(f"Du {data_info['first_date']} au {data_info['last_date']}")
                else:
                    st.error("❌ Aucune donnée disponible")
            
            with col2:
                st.subheader("🤖 Modèles")
                if status.get("models", {}).get("available", False):
                    model_info = status["models"]
                    st.success("✅ Modèles disponibles")
                    if model_info.get("trained_at"):
                        st.caption(f"Entraînés le: {model_info['trained_at']}")
                else:
                    st.error("❌ Aucun modèle entraîné")
            
            # Recommendations
            recommendations = status.get("recommendations", [])
            if recommendations:
                st.subheader("💡 Recommandations")
                for rec in recommendations:
                    st.info(f"• {rec}")
            
            # Smart Alerts
            st.subheader("🔔 Alertes Intelligentes")
            
            from repository import get_repository
            repo = get_repository()
            draws = repo.all_draws_df()
            
            if not draws.empty:
                last_draw_date = datetime.fromisoformat(draws.iloc[-1]['draw_date'])
                days_since = (datetime.now() - last_draw_date).days
                
                if days_since > 7:
                    st.warning(f"⚠️ Dernière mise à jour il y a {days_since} jours - Rafraîchissement recommandé")
                else:
                    st.success(f"✅ Données à jour ({days_since} jours)")
            
            if status.get("models", {}).get("available"):
                model_date = status["models"].get("trained_at", "")
                if model_date:
                    trained_at = datetime.fromisoformat(model_date.split("T")[0])
                    days_old = (datetime.now() - trained_at).days
                    if days_old > 30:
                        st.warning(f"⚠️ Modèles entraînés il y a {days_old} jours - Réentraînement recommandé")
                    
        except Exception as e:
            st.error(f"❌ Erreur lors de la récupération du statut: {e}")


if __name__ == "__main__":
    main()
